<a href="https://colab.research.google.com/github/Endcru/MatStatIDZ/blob/main/hw1_2023_Konstantinov_Nikita_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HSE 2023: Mathematical Methods for Data Analysis

## Homework 1

### Attention!
* For tasks where <ins>text answer</ins> is required **Russian language** is **allowed**.
* If a task asks you to describe something (make conclusions) then **text answer** is **mandatory** and **is** part of the task
* **Do not** upload the dataset (titanic.csv) to the grading system (we already have it)
* We **only** accept **ipynb** notebooks. If you use Google Colab then you'll have to download the notebook before passing the homework
* **Do not** use python loops instead of NumPy vector operations over NumPy vectors - it significantly decreases performance (see why https://blog.paperspace.com/numpy-optimization-vectorization-and-broadcasting/), will be punished with -0.25 for **every** task.
Loops are only allowed in part 1 (Tasks 1 - 4).
* Some tasks contain tests. They only test your solution on a simple example, thus, passing the test does **not** guarantee you the full grade for the task.

In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Python (2 points)

**Task 1** (0.5 points)<br/>
Enter nonzero numbers `a`, `d` and `N`. Find the sum of the first `N` members of [harmonic sequence](https://en.wikipedia.org/wiki/Harmonic_progression_(mathematics)) with the first member denominator `a`

In [ ]:
def find_sum(a: int, d: int, N: int) -> float:
    result = 0
    for i in range (0, N):
        result += 1 / (a + i * d)
    return result

a = 1
d = 1
N = 10
print(find_sum(a, d, N))

2.9289682539682538


**Task 2** (0.5 points) <br/>
Enter an integer number `N`. Check if it is a palindrome number **without converting it to the string**. It means that it can be read equally from left to right and from right to back.

In [ ]:
def check_palindrome(N):
    a = N
    b = 0
    while (a > 0):
        b = b * 10 + a % 10
        a //= 10
        check_palindrome = b == N
    return check_palindrome

for N in [3, 81, 111, 113, 810, 2022, 4774, 51315, 611816]:
    print(N, check_palindrome(N))

3 True
81 False
111 True
113 False
810 False
2022 False
4774 True
51315 True
611816 False


**Task 3** (0.5 points) <br/>
Find the first `N` palindrome numbers starting from 42 (you may use the function from the precious task).

In [ ]:
def find_palindromes(N):
    k = 0
    i = 42
    palindromes = []
    while k < N:
        if check_palindrome(i):
            k += 1
            palindromes.append(i)
        i += 1
    return palindromes

print(find_palindromes(3))
print(find_palindromes(13))
print(find_palindromes(23))

[44, 55, 66]
[44, 55, 66, 77, 88, 99, 101, 111, 121, 131, 141, 151, 161]
[44, 55, 66, 77, 88, 99, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202, 212, 222, 232, 242, 252, 262]


**Task 4** (0.5 points) <br/>
There are numbers: `a`, `b`, `c`. Without using functions `min`, `max` and other functions, find the median number.

In [ ]:
from random import randint

def find_median(a, b, c):
    if a > b:
        b, a = a, b
    if a > c:
        a, c = c, a
    if b > c:
        b, c = c, b
    if a == b:
        b = (c + b) / 2
    if b == c:
        b = (a + b) / 2
    return b

for i in range(10):

    a = randint(-100, 100)
    b = randint(-100, 100)
    c = randint(-100, 100)

    print(a, b, c, '\tMedian:', find_median(a, b, c))

76 49 45 	Median: 49
35 48 -32 	Median: 35
-58 -26 -94 	Median: -58
78 63 -76 	Median: 63
22 45 41 	Median: 41
76 67 11 	Median: 67
-45 -73 44 	Median: -45
93 98 -65 	Median: 93
-38 55 53 	Median: 53
17 75 -72 	Median: 17


# 2. Numpy (4 points)

**Task 1** (0.5 points) <br/>
Create a random array from Gaussian distribution with length of 12 and with sum of its elements equal to 15. Distribution shall be left Gaussian

In [ ]:
my_array = []
while not (-0.0001 < (np.sum(my_array) - 15) < 0.0001):
    my_array = np.random.normal(loc = 2, size=12)
print(my_array)
print(f'Length: {len(my_array)}')
print(f'Sum of elements: {np.sum(my_array)}')

[ 0.91280355  1.61966753  2.38092376  1.56898127 -0.16142474 -0.00775585
  0.57799356 -0.37172625  2.75329552  2.08389102  0.9985606   2.64487214]
Length: 12
Sum of elements: 15.000082101594076


**Task 2** (0.5 points) <br/>
Create two random arrays $a$ and $b$ with the same length.

Calculate the following distances between the arrays **without using any special function. You may only use basic numpy operations (`np.linalg.*` and other high-level ones are prohibited).**:

* Manhattan Distance
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Euclidean Distance
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Chebyshev Distance
$$ d(a, b) = \underset{i}{max} |a_i - b_i| $$
* Cosine Distance
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2} $$


In [ ]:
def calculate_manhattan(a, b):
    c = np.abs(a - b)
    distance = c.sum()
    return distance

def calculate_euclidean(a, b):
    c = (a - b) * (a - b)
    distance = np.sqrt(c.sum())
    return distance

def calculate_chebyshev(a, b):
    c = np.abs(a - b)
    distance = c.max()
    return distance

def calculate_cosine(a, b):
    distance = 1 - (a.T.dot(b)) / (np.linalg.norm(a, ord=2) * np.linalg.norm(b, ord=2))
    return distance

In [ ]:
np.random.seed(42)
a = np.random.randint(1,100,5)
b = np.random.randint(1,100,5)
print(a, b)
print(f'Manhattan distance: {calculate_manhattan(a, b)}')
print(f'Euclidean distance: {calculate_euclidean(a, b)}')
print(f'Chebyshev distance: {calculate_chebyshev(a, b)}')
print(f'Cosine distance: {calculate_cosine(a, b)}')

[52 93 15 72 61] [21 83 87 75 75]
Manhattan distance: 130
Euclidean distance: 80.31189202104505
Chebyshev distance: 72
Cosine distance: 0.13188506348165574


**Task 3** (0.5 points) <br/>
Create a random array of integers with length of 42. Transform the array so that
* Maximum element(s) value is 10
* Minimum element(s) value is -6
* Other values are in interval (-6; 10) without changing the relative order (relation $\frac{x_i}{x_{i-1}}=\frac{\widehat{x}_{i}}{\widehat{x}_{i-1}}$ holds)

In [ ]:
def transform(array):
    transformed_array = array[(array <= 10) & (array >= -6)]
    return transformed_array

In [ ]:
my_array = np.random.randint(-20, 20, 42)
print('Start Array:')
print(my_array)
my_array = transform(my_array)
print(f'Min: {np.min(my_array)}')
print(f'Max: {np.max(my_array)}')
print('Array:')
print(my_array)

Start Array:
[  3  15  19   3 -18   1 -19   3   9  17 -19   0  12  -9   1   4   6   7
  -5  -6 -18  16 -14   0 -12  18  -3 -17   4  -7 -12   5 -19  -1   7 -14
 -13  14  -7  -4  15  19]
Min: -6
Max: 9
Array:
[ 3  3  1  3  9  0  1  4  6  7 -5 -6  0 -3  4  5 -1  7 -4]


**Task 4** (0.5 points) <br/>
Create an array with shape of $10 \times 3$ with integers from [-12, 4]. Find a column that contains the minimum element of the array.

In [ ]:
my_array = np.random.randint(low=-12, high=4, size=(10,3))
selected_column = my_array.min()
print('Shape: ', my_array.shape)
print('Array:')
print(my_array)
print(f'Selected column: {selected_column}')

Shape:  (10, 3)
Array:
[[ -6  -4  -5]
 [ -1 -11 -12]
 [  3  -6  -6]
 [  1  -5  -8]
 [-10  -1  -5]
 [ -7  -2 -10]
 [-12 -10  -8]
 [  2   1 -10]
 [-12  -8  -3]
 [ -6   2   1]]
Selected column: -12


**Task 5** (0.5 points) <br/>

Replace all missing values in the following array with the most appropriate quantile, explain why you chose it.

In [ ]:
arr = np.random.rand(10)
idx = np.random.randint(0, 10, 4)
arr[idx] = np.nan

print('Array:')
print(arr)

Array:
[0.72408531        nan 0.22909646 0.11720183 0.44445196        nan
        nan 0.81487031 0.29969807 0.00206668]


In [ ]:
def replace_missing(arr):
    ## Your code here
    return array_without_missing

In [ ]:
arr = replace_missing(arr)
print('Array with no missing values:')
print(arr)

**Answer:** here

**Task 6** (0.5 points) <br/>
Create a function which takes an image ```X``` (3D array of the shape (n, m, 3)) as an input and returns the median and std for every channel (you should get a vector of shape 3, RGB).

In [ ]:
def stats_channel(X):
    # Your code here
    return median, std

In [ ]:
n = 19
m = 23
X = np.random.randint(-11, 8, size=(n, m, 3))
print(X)
print(stats_channel(X))

[[[-11   1  -5]
  [ -7  -4   2]
  [  1   3   5]
  ...
  [ -1   6  -8]
  [ -9   1  -3]
  [ -6   0 -10]]

 [[ -9  -9   0]
  [  3  -3  -4]
  [ -1   4  -8]
  ...
  [  6  -3   5]
  [  1   3   5]
  [  1   4  -8]]

 [[ -7  -7  -3]
  [  5   1 -10]
  [  1   7  -9]
  ...
  [  0  -6  -8]
  [ -6  -1 -11]
  [  3  -1   7]]

 ...

 [[-11 -10   4]
  [  3   1   4]
  [  5  -5   5]
  ...
  [  1   1   3]
  [ -2  -9   7]
  [ -9   2  -4]]

 [[ -8  -1  -1]
  [ -1 -10   5]
  [ -3 -10   3]
  ...
  [-11   1   2]
  [  1  -8  -5]
  [ -2  -5   3]]

 [[  3  -8  -6]
  [ -7   0 -11]
  [ -4 -11  -7]
  ...
  [  7  -1 -10]
  [ -2  -1   4]
  [  7  -1   2]]]


NameError: ignored

### **Task 7** (1 points) <br/>
Create a function which takes a 3D matrix ```X``` as an input and returns all its unique values along the first axis.

Sample input:

```
np.array(
  [[[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]],

   [[4, 5, 6],
    [4, 5, 7],
    [4, 5, 6]],

   [[7, 8, 9],
    [7, 8, 9],
    [7, 8, 9]]]
)
```
  
Sample output:

```
np.array(
  [[[1, 2, 3],
    [1, 2, 3]],

   [[4, 5, 6],
    [4, 5, 7]],

   [[7, 8, 9],
    [7, 8, 9]]]
)
```

In [ ]:
def get_unique_values(X):
    ## Your code here
    return result

In [ ]:
X =  np.random.randint(4, 6, size=(n, 3, 3))
print('Matrix:')
print(X)
print('Unique :')
get_unique_values(X)

# 3. Pandas & Visualization (4 points)


You are going to work with *Titanic* dataset which contains information about passengers of Titanic:
- **Survived** - 1 - survived, 0 - died (0); **Target variable**
- **pclass** - passengers's class;
- **sex** - passengers's sex
- **Age** - passengers's age in years
- **sibsp**    - is the passenger someones siblings   
- **parch**    - is the passenger someones child or parent
- **ticket** - ticket number    
- **fare** - ticket price    
- **cabin** - cabin number
- **embarked** - port of Embarkation; C = Cherbourg, Q = Queenstown, S = Southampton

**Note** for all visualizations use matplotlib or seaborn but NOT plotly! Plotly's graphics sometimes vanish after saving. In this case the task won't be graded.

**Note** support all your answers with necessary code, computations, vizualization, and explanation. Answers without code and explanation won't be graded.

**Task 0** (0 points) \
Load the dataset and print first 6 rows

In [ ]:
dataset = pd.read_csv('titanic.csv')
## Your code here

FileNotFoundError: ignored

**Task 1** (1 points) <br/>
Answer the following questions:
    
    * Are there any missing values? In what columns?
    * What is the percentage of survived passengers? Are the classes balanced?
    * Were there more males or females?
    * What what the least popular port of embarkation?
    * How many passenger classes (pclass) were there on Tinanic?
    * What is the overall average ticket fare? And for every passenger class?
Please, write not only the answers but the code, proving it.

In [ ]:
## Your code here

**Task 2** (0.5 points) <br/>
Visualize age distribution (you may use a histogram, for example).

    * What is the minimal and maximum ages of the passengers? Visualize it on the plot
    * What is the median age? And among males and females separately? Visualize it on the separate plot
    * Make conclusions about what you see on the plots

In [ ]:
## Your code here

**Task 3** (1 points) <br/>
Find all the titles of the passengers (example, *Capt., Mr.,Mme.*), which are written in the column Name, and answer the following questions:

    * How many are there unique titles?
    * How many are there passengers with every title?
    * What is the most popular man's title? And woman's title?
    
**Hint** You may select the title from the name as a word which contains a dot and is not middle name.

In [ ]:
## Your code here

**Task 4** (0.5 points) <br/>
Is there correlation between *pclass* and *ticket price*? Calculate mean price for each class and visualize price distribution for each class as well. Make conclusions about what you see on the plot

Hint: you could make one or several plot types i.e.  box, violine, pair, histogram (see additional notebooks for Seminar 1 "Visualization with Seaborn"). Main point here is to **choose** plots wisely and **make meaningful conclusions**



In [ ]:
## You code here

**Task 5** (0.5 points) <br/>
The same question as in task 4 about correlation between *embarked* and *ticket priсe*.

In [ ]:
## You code here

**Task 6** (0.5 points) <br/>
Visualize age distribution for survived and not survived passengers separately and calculate the mean age for each class. Are they different? Provide the same visualization for males and females separately. Make conclusions about what you see on the plots

In [ ]:
## You code here